name: Terraform Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Specifies the environment of the deployment."
      runner_label:
        required: false
        type: string
        description: "Specifies the runner label."
        default: "self-hosted"
      config:
        required: true
        type: string
        description: "Specifies the configuration folder for the deployment."
      terraform_version:
        required: true
        type: string
        description: "Specifies the terraform version."
      node_version:
        required: true
        type: number
        description: "Specifies the node version."
      tenant_id:
        required: true
        type: string
        description: "Specifies the tenant id of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the subscription id of the deployment."
      run_azure_login:
        required: false
        type: boolean
        description: "Specifies whether the test should be executed."
        default: false
      run_test:
        required: false
        type: boolean
        description: "Specifies whether the test should be executed."
        default: true
      log_level_test:
        required: false
        type: string
        description: "Specifies the log level for the test run."
        default: "ERROR"
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Terraform Lint
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: true

      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Terraform Format
      - name: Terraform Format
        id: terraform_format
        working-directory: "./modules/${{ inputs.config }}"
        run: |
          terraform fmt -check -recursive

      # Add Pull Request Comment
      - name: Add Pull Request Comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: pr_comment
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Lint Results
            * Terraform Version ðŸ“Ž\`${{ inputs.terraform_version }}\`
            * Working Directory ðŸ“‚\`./modules/${{ inputs.config }}\`
            * Terraform Format and Style ðŸ–Œ\`${{ steps.terraform_format.outcome }}\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  test:
    name: Terraform Test
    runs-on: ${{ inputs.runner_label }}
    continue-on-error: false
    environment: ${{ inputs.environment }}
    if: inputs.run_test
    needs: [lint]
    concurrency:
      group: terraform-test-${{ inputs.config }}-${{ inputs.environment }}
      cancel-in-progress: false

    env:
      ARM_TENANT_ID: ${{ inputs.tenant_id }}
      ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_USE_OIDC: true
      FABRIC_TENANT_ID: ${{ inputs.tenant_id }}
      FABRIC_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      FABRIC_USE_OIDC: true

    steps:
      # Setup Node
      - name: Setup Node
        id: node_setup
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ inputs.node_version }}

      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: true

      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Azure login
      - name: Azure login
        id: azure_login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        if: inputs.run_azure_login
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      # Terraform Override
      - name: Terraform Override
        run: |
          mv code/utilities/terraform_override.tf modules/${{ inputs.config }}

      # Terraform Init
      - name: Terraform Init
        id: terraform_init
        working-directory: "./modules/${{ inputs.config }}"
        run: |
          terraform init

      # Terraform Test
      - name: Terraform Test
        id: terraform_test
        working-directory: "./modules/${{ inputs.config }}"
        run: |
          terraform test
        env:
          TF_LOG: ${{ inputs.log_level_test }}

      # Add Pull Request Comment
      - name: Add Pull Request Comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: pr_comment
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Test Results
            * Terraform Version ðŸ“Ž\`${{ inputs.terraform_version }}\`
            * Working Directory ðŸ“‚\`./modules/${{ inputs.config }}\`
            * Terraform Tests ðŸ–Œ\`${{ steps.terraform_test.outcome }}\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
