name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Setup Python
      - name: Setup Python
        id: python_setup
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.14.1"
          terraform_wrapper: true

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Run Linting
      - name: Run Linting
        id: linting
        run: |
          echo "Install dependencies"
          python3 -m pip install -r requirements.txt -q

          echo "Initialize Git"
          git init
          git add *

          echo "Run pre-commit"
          python3 -m pre_commit install --install-hooks
          python3 -m pre_commit run --all-files --verbose
